### ISSUE TITLE
Overview + moneroblocks.info is broken

### ISSUE THREAD

**Issue by mranostay** [micro-machine/monero-monitor#11]
Failed to load https://moneroblocks.info/api/get_stats: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'chrome-extension://pkmhdjoniodhnknaagnlbkpbcjdfmeki' is therefore not allowed access.
Failed to load https://moneroblocks.info/api/get_stats/: Redirect from 'https://moneroblocks.info/api/get_stats/' to 'https://moneroblocks.info/api/get_stats' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'chrome-extension://pkmhdjoniodhnknaagnlbkpbcjdfmeki' is therefore not allowed access.

**Comment by moonwater** [comment]
And the market tab is broken partially. 
![cc11](https://user-images.githubusercontent.com/3188430/70108696-de579f80-1684-11ea-8d30-2b20d56cad6d.png)
![cc12](https://user-images.githubusercontent.com/3188430/70108698-de579f80-1684-11ea-853d-ca528912ec06.png)
