### ISSUE TITLE
Overview No Longer Working

### ISSUE THREAD

**Issue by djjacket** [micro-machine/monero-monitor#8]
The overview page is not showing data, but the reddit and Markets sections are accurate.

![image](https://cloud.githubusercontent.com/assets/11663298/21942445/241cab3e-d99b-11e6-92a5-aad4aab1a956.png)

**Comment by bigreddmachine** [comment]
Thanks, noticed this last night. I'll get it fixed by tomorrow!

**Comment by djjacket** [comment]
Awesome - thanks for this nice tool

**Comment by bigreddmachine** [comment]
Fixed in 7805e506a71a2dcf661b4e16f7fdeac8e4fcfa37

A new release (v1.3.0) has been pushed to the Chrome Store and should update within 24 hours for you! It also includes some new features :)
